server:
  port: 8080

spring:
  application:
    name: bankaccount
  config:
    import:
      - classpath:database/h2.yml

axon:
  axonserver:
    enabled: false
  serializer:
    general: xstream

#axon:
#  serializer:
#    general: xstream
#    messages: xstream
#    events: jackson

springdoc:
  swagger-ui:
    path: "/swagger-ui.html"
