spring:
  datasource:
    url: jdbc:h2:mem:example;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console

h2:
  enabled: true
  tcp:
    enabled: true
  web:
    enabled: true
