version: '3'
# https://hub.docker.com/r/axoniq/axonserver
services:
  axon-server:
    image: axoniq/axonserver:4.4.6
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true
    ports:
      - "8024:8024"
      - "8124:8124"
