version: '3.3'
# https://hub.docker.com/r/axoniq/axonserver
services:
  axon-server:
    image: axoniq/axonserver:4.5.4.1
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true
      - SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE=32MB
      - SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE=32MB
    ports:
      - "8024:8024"
      - "8124:8124"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: apicurio-registry
      POSTGRES_PASSWORD: password
  registry:
    hostname: apicurio
    image: apicurio/apicurio-registry-sql:2.0.1.Final
    expose:
      - "8080"
    ports:
      - "7777:8080"
    environment:
      REGISTRY_DATASOURCE_URL: 'jdbc:postgresql://postgres/apicurio-registry'
      REGISTRY_DATASOURCE_USERNAME: apicurio-registry
      REGISTRY_DATASOURCE_PASSWORD: password
