name: Development branches

on:
  push:
    branches:
      - '*'
      - '**/*'
      - '!master'
      - '!release/*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and run tests on JDK 11
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Expose branch name
        run: echo ${{ github.ref }}

      # Setup the cache
      - name: Cache .m2
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Setup JDK and Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: ossrh
          server-username: OSS_CENTRAL_USERNAME # env variable for Maven Central
          server-password: OSS_CENTRAL_PASSWORD # env variable for Maven Central

      # Prepare
      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      # Build
      - name: Build with Maven
        run: ./mvnw clean verify -U -B -T4

      # I-Test
      - name: Run I-Test
        run: ./mvnw verify -Pitest -U -B -T4

      # Code analysis
      - name: Upload coverage to Codecov
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Upload coverage to Codacy
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: examples/coverage-aggregate/target/site/jacoco-aggregate/jacoco.xml
